### PR TITLE
175969887-flutter-web

### PR DESCRIPTION
**Pull request by rameshwarikodam**
**What does this PR do?**
This PR indicates a web-based view of visitafri.

**Description of Task to be completed?**
This is only the configuration of the web app. Users are now able to run the application of the website.

**How should this be manually tested?**
-Clone it using this link [https://github.com/Soma-Technologies-Inc/visitAfrica-frontend.git](url)
-Run flutter "pub get" to install dependencies.
-Run it by using the "flutter run -d chrome --release" command in any text editor you want.

**Any background context you want to provide?**
-Follow these steps before viewing the app on chrome:
> flutter channel beta

> flutter upgrade

> flutter config --enable-web 

> Add web support to an existing app using the "flutter create . " command.

> If you stuck somewhere follow [official documentation](https://flutter.dev/docs/get-started/web).

**What are the relevant pivotal tracker stories?**
-[175969887](https://www.pivotaltracker.com/story/show/175969887)

HomePage
homepage1
MainPage
sihnUp

### CODE REVIEW

**Review by VedaDom — APPROVED** [review]

**Review by Sandrine21 — COMMENTED** [review]
Please, can you rename your PR by following this format `#[STORY_ID] Story description`.

**Comment by rameshwarikodam** [comment]
> Please, can you rename your PR by following this format `#[STORY_ID] Story description`.

sure

**Comment by dianahub250** [comment]
You have done a great work Rameshwari, would you mind checking on teammates' PR and change the way of providing the link of pivot tracker story and also on how it should be manually tested try to differentiate commands with other words in the sentences.

**Review by dianahub250 — CHANGES_REQUESTED** [review]
You have done a great work Rameshwari, would you mind checking on teammates' PR and change the way of providing the link of pivot tracker story and also on how it should be manually tested try to differentiate commands with other words in the sentences.

**Comment by rameshwarikodam** [comment]
> You have done great work Rameshwari, would you mind checking on teammates' PR and change the way of providing the link of pivot tracker story and also on how it should be manually tested to try to differentiate commands with other words in the sentences.

Thanks for reviewing my PR. I will make the changes in my PR.

**Pull request closed without merging**
